<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            ['employee_number' => '21',  'name' => 'Carlos Alberto Da Cruz Guerreiro',                  'role' => 'electrician'],
            ['employee_number' => '25',  'name' => 'Rui Vasco Costa Nunes Dos Santos',                  'role' => 'electrician'],
            ['employee_number' => '101', 'name' => 'Paulo Jorge Silva Santos',                           'role' => 'electrician'],
            ['employee_number' => '104', 'name' => 'Eureliano Flávio Casquinha Barreto',                 'role' => 'ironworker'],
            ['employee_number' => '114', 'name' => 'Óscar Manuel Pereira Da Silva',                      'role' => 'electrician_foreman'],
            ['employee_number' => '130', 'name' => 'Fredric Eric Assunção Kouprianoff',                  'role' => 'electrician'],
            ['employee_number' => '153', 'name' => 'Bruno Macario R. Gaspar Gonçalves',                  'role' => 'ironworker_foreman'],
            ['employee_number' => '154', 'name' => 'Carlos Casimiro Alves Ferreira',                     'role' => 'electrician_foreman'],
            ['employee_number' => '156', 'name' => 'Manuel Júlio Duarte Ribeiro',                        'role' => 'ironworker_foreman'],
            ['employee_number' => '172', 'name' => 'Alfredo José Rosa Marques',                          'role' => 'electrician'],
            ['employee_number' => '176', 'name' => 'José Carlos Rosado Chaminé',                         'role' => 'ironworker_foreman'],
            ['employee_number' => '186', 'name' => 'Tomasz Wisniewski',                                  'role' => 'ironworker'],
            ['employee_number' => '208', 'name' => 'Paulo Sergio Martins Nunes',                         'role' => 'electrician'],
            ['employee_number' => '214', 'name' => 'Armando Manuel Ferreira Franco',                     'role' => 'supervisor'],
            ['employee_number' => '225', 'name' => 'Valter José Zeferino Santos Abreu',                  'role' => 'ironworker'],
            ['employee_number' => '226', 'name' => 'Artur Jorge Pinto Correia',                          'role' => 'electrician'],
            ['employee_number' => '232', 'name' => 'André Manuel Fialho Teixeira',                       'role' => 'ironworker'],
            ['employee_number' => '243', 'name' => 'Vitor Manuel Pereira Andrade',                       'role' => 'ironworker'],
            ['employee_number' => '260', 'name' => 'Ivo Guilherme Curado Miranda',                       'role' => 'electrician'],
            ['employee_number' => '278', 'name' => 'Rui Jorge Gaspar Quendera',                          'role' => 'electrician_foreman'],
            ['employee_number' => '279', 'name' => 'Carlos Fernando Aguiar Henriques',                   'role' => 'ironworker'],
            ['employee_number' => '280', 'name' => 'Pedro Nuno Filipe Sabino',                           'role' => 'electrician'],
            ['employee_number' => '302', 'name' => 'Hélder Manuel Marques Pinto',                        'role' => 'ironworker'],
            ['employee_number' => '303', 'name' => 'António Gustavo Dias Anjos Costa',                   'role' => 'electrician'],
            ['employee_number' => '304', 'name' => 'António João Da Silva Ferreira',                     'role' => 'electrician'],
            ['employee_number' => '307', 'name' => 'Pedro Miguel Jacinto De Sousa',                      'role' => 'supervisor'],
            ['employee_number' => '308', 'name' => 'João Manuel Nunes Marques',                          'role' => 'electrician'],
            ['employee_number' => '322', 'name' => 'Ruben Miguel Baião Marques',                         'role' => 'electrician_foreman'],
            ['employee_number' => '323', 'name' => 'Evanilson David Varela Mendes',                      'role' => 'electrician'],
            ['employee_number' => '330', 'name' => 'Nuno Miguel Casquinha Dias',                         'role' => 'electrician'],
            ['employee_number' => '338', 'name' => 'Leandro Lima Oliveira',                              'role' => 'ironworker'],
            ['employee_number' => '351', 'name' => 'Ricardo Manuel Silva Dias',                          'role' => 'ironworker'],
            ['employee_number' => '355', 'name' => 'Tiago Miguel Lopes Marques',                         'role' => 'electrician'],
            ['employee_number' => '361', 'name' => 'Fernando Francisco Tavares',                         'role' => 'electrician'],
            ['employee_number' => '364', 'name' => 'Gregório Paulo Pereira Teixeira',                    'role' => 'electrician'],
            ['employee_number' => '366', 'name' => 'Valentyn Raylyan',                                   'role' => 'electrician'],
            ['employee_number' => '373', 'name' => 'Catalin Doina',                                      'role' => 'electrician'],
            ['employee_number' => '375', 'name' => 'Vitor Luís Rosa Dutra Esteves',                      'role' => 'electrician'],
            ['employee_number' => '385', 'name' => 'Mário André Pereira Vinhas',                         'role' => 'electrician'],
            ['employee_number' => '386', 'name' => 'Afonso Dos Santos Fernandes',                        'role' => 'electrician'],
            ['employee_number' => '388', 'name' => 'Vladyslav Brykalov',                                 'role' => 'ironworker'],
            ['employee_number' => '393', 'name' => 'Henrique Jorge Lourenço Fernandes',                  'role' => 'electrician'],
            ['employee_number' => '394', 'name' => 'Miguel Ângelo Rodrigues Nóbrega',                    'role' => 'electrician'],
            ['employee_number' => '398', 'name' => 'Jorge Lucas Teixeira Ferreira',                      'role' => 'electrician'],
            ['employee_number' => '410', 'name' => 'Bohdan Hreshchuk',                                   'role' => 'electrician'],
            ['employee_number' => '411', 'name' => 'Ricardo Jorge Gomes Matos',                          'role' => 'electrician'],
            ['employee_number' => '414', 'name' => 'Joaquim Manuel Pinto Alexandre',                     'role' => 'electrician'],
            ['employee_number' => '419', 'name' => 'Sergey Kaminskiy',                                   'role' => 'electrician'],
            ['employee_number' => '437', 'name' => 'António José da Rosa Veiga Nunes',                   'role' => 'electrician'],
            ['employee_number' => '438', 'name' => 'Victor Manuel Lara Jimeno',                          'role' => 'technician'],
            ['employee_number' => '443', 'name' => 'Carlos Augusto Gomes Sousa',                         'role' => 'electrician'],
            ['employee_number' => '454', 'name' => 'Telmo Daniel Teixeira Andrade',                      'role' => 'ironworker'],
            ['employee_number' => '464', 'name' => 'João Filipe Dos Santos Almeida',                     'role' => 'electrician'],
            ['employee_number' => '473', 'name' => 'Robert Wolanczyk',                                   'role' => 'electrician'],
            ['employee_number' => '483', 'name' => 'Filipe Manuel Póvoa Marabuto',                       'role' => 'ironworker'],
            ['employee_number' => '484', 'name' => 'Hélcio Wanderley Rodrigues Alves',                   'role' => 'electrician'],
            ['employee_number' => '487', 'name' => 'João Miguel Leal Catarino',                          'role' => 'electrician_foreman'],
            ['employee_number' => '488', 'name' => 'José Martins Dias',                                  'role' => 'electrician'],
            ['employee_number' => '492', 'name' => 'Sérgio De Moura Rodrigues',                          'role' => 'electrician'],
            ['employee_number' => '494', 'name' => 'Stanislav Dyachenko',                                'role' => 'electrician'],
            ['employee_number' => '499', 'name' => 'Cláudio Alexandre da Conceição Pereira',             'role' => 'electrician'],
            ['employee_number' => '500', 'name' => 'Rui Leão Castanheira',                               'role' => 'electrician'],
            ['employee_number' => '504', 'name' => 'João Pedro de Almeida Couto',                        'role' => 'electrician'],
            ['employee_number' => '511', 'name' => 'Jorge Ricardo Nóbrega Franco',                       'role' => 'ironworker'],
            ['employee_number' => '512', 'name' => 'Flávio Pedro Fortes Neves',                          'role' => 'electrician'],
            ['employee_number' => '514', 'name' => 'Petre Ionut Birsa',                                  'role' => 'electrician'],
            ['employee_number' => '515', 'name' => 'Andrew Miranda Cavalcante',                          'role' => 'electrician'],
            ['employee_number' => '516', 'name' => 'Simão Alexandre Salvador Tavares',                   'role' => 'electrician'],
            ['employee_number' => '518', 'name' => 'Stefan Totos',                                       'role' => 'electrician'],
            ['employee_number' => '519', 'name' => 'António Jorge Lago Mendes',                          'role' => 'electrician'],
            ['employee_number' => '520', 'name' => 'Sérgio Miguel Valezim Dias',                         'role' => 'ironworker'],
            ['employee_number' => '524', 'name' => 'João Miguel Da Costa Mendes',                        'role' => 'ironworker'],
            ['employee_number' => '525', 'name' => 'Emanuel Gonçalves Pereira dos Reis',                 'role' => 'electrician'],
            ['employee_number' => '526', 'name' => 'Paulo Alexandre Vargas Loureiro Mendes Tapadinhas',  'role' => 'electrician'],
            ['employee_number' => '527', 'name' => 'Marin Trandafir',                                    'role' => 'electrician_foreman'],
            ['employee_number' => '528', 'name' => 'Délcio Josinori De Carvalho Bandola',                'role' => 'electrician'],
            ['employee_number' => '529', 'name' => 'Richard Gabriel Andrade Ponte',                      'role' => 'technician'],
            ['employee_number' => '530', 'name' => 'Edgar Vila Nova Lixa',                               'role' => 'ironworker'],
            ['employee_number' => '531', 'name' => 'Flávio João Bolinhas Ribeiro',                       'role' => 'ironworker'],

            // From original seeder — no employee number found in table data
            ['employee_number' => null,  'name' => 'Idloy Domingos',                                     'role' => 'electrician'],
            ['employee_number' => null,  'name' => 'César Prata',                                        'role' => 'electrician'],
            ['employee_number' => null,  'name' => 'Paulo Silvestre',                                     'role' => 'ironworker'],
            ['employee_number' => null,  'name' => 'Dawid Olbrich',                                      'role' => 'ironworker'],
            ['employee_number' => null,  'name' => 'José Manuel Fialho Martins',                         'role' => 'electrician'],
        ];

        DB::table('employees')->insertOrIgnore($employees);
    }
}
