<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tools = [
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => '8X150 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 7],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => '5,5X125 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => '4,0X100 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 9],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => '3,5X100 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 3],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => '2,5X75 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 4],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => 'PZ2 AD', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 4],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => 'PZ1 AD', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 14],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => 'PZ0 AD', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => 'PH0 AP', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => 'PH1 AP', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 3],
            ['name' => 'Insulated screwdriver', 'brand' => 'Facom', 'type' => 'PH2 AP', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 1],
            ['name' => 'Voltage tester screwdriver', 'brand' => 'Carolus', 'type' => 'yt-0404', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5],
            ['name' => 'Small phillips screwdriver', 'brand' => 'Facom', 'type' => 'PH1 X 25', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 3],
            ['name' => 'Small phillips screwdriver', 'brand' => 'Facom', 'type' => 'PH2 X 35', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5],
            ['name' => 'Small flathead screwdriver', 'brand' => 'Facom', 'type' => '6,5X35', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 8],
            ['name' => 'Small flathead screwdriver', 'brand' => 'Facom', 'type' => '5,5X35', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 1],
            ['name' => 'Small flathead screwdriver', 'brand' => 'Facom', 'type' => '4X25', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 4],
            ['name' => 'Flathead screwdriver', 'brand' => 'Facom', 'type' => 'ANF 8x150', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 11],
            ['name' => 'Flathead screwdriver', 'brand' => 'Facom', 'type' => 'ANF 6,5 x 150', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 24],
            ['name' => 'Flathead screwdriver', 'brand' => 'Facom', 'type' => 'AN5,5X125', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 21],
            ['name' => 'Flathead screwdriver', 'brand' => 'Facom', 'type' => 'AN4,0X100', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 17],
            ['name' => 'Flathead screwdriver', 'brand' => 'Facom', 'type' => 'AN3,5X75', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 6],
            ['name' => 'Pozidriv screwdriver', 'brand' => 'Facom', 'type' => 'PZ1 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 14],
            ['name' => 'Pozidriv screwdriver', 'brand' => 'Facom', 'type' => 'PZ2 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 6],
            ['name' => 'Phillips screwdriver', 'brand' => 'Facom', 'type' => 'PH1 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 7],
            ['name' => 'Phillips screwdriver', 'brand' => 'Facom', 'type' => 'PH2 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 5],
            ['name' => 'Universal pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'shared', 'amount_in_stock' => 19],
            ['name' => 'Cutting pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'shared', 'amount_in_stock' => 6],
            ['name' => 'Electronic cutting pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Curved nose pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 17],
            ['name' => 'Self-adjusting crimping pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 4],
            ['name' => 'Terminal crimping pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Wire stripping pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 8],
            ['name' => 'Special wire stripping pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 2],
            ['name' => 'Pliers wrench', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Sleeving pliers', 'brand' => 'Facom', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 7],
            ['name' => 'Cable shears', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 6],
            ['name' => 'Tube cutter', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 12],
            ['name' => 'Waterpump pliers', 'brand' => 'Knipex', 'type' => '', 'category' => 'Pliers', 'roletype' => 'ironworker', 'amount_in_stock' => 9],
            ['name' => 'Crimping pliers', 'brand' => 'Weldmuller', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 1],
            ['name' => 'Drill bit set 1-13mm', 'brand' => 'Labor', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '10mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '8mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '6mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '5mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '4mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '3mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '2.5mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '2mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Hex key', 'brand' => 'Facom', 'type' => '1.5mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '6mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 13],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '7mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '8mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 14],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '9mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 14],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '10mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '11mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '12mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '13mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 3],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '15mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '17mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 3],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '19mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '22mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15],
            ['name' => 'Ratchet socket', 'brand' => 'Promat', 'type' => '24mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15],
            ['name' => 'Ratchet socket 3/8"', 'brand' => 'Promat', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 12],
            ['name' => 'Small extension', 'brand' => 'Promat', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 4],
            ['name' => 'Large extension', 'brand' => 'Promat', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11],
            ['name' => 'Universal joint', 'brand' => 'Promat', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 12],
            ['name' => 'Ratchet', 'brand' => 'Promat', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '19mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '18mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '17mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '16mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '13mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '12mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '11mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '10mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Combination wrench', 'brand' => 'Facom', 'type' => '8mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Toolcase', 'brand' => 'Facom', 'type' => 'BS T20BP', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Tool backpack', 'brand' => 'Stanley', 'type' => 'Fat-Max', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => '5M measuring tape', 'brand' => 'Gedore', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Caliper', 'brand' => 'Mitutoyo', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Hammer', 'brand' => 'Facom', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 1],
            ['name' => 'Level', 'brand' => 'Promat', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 16],
            ['name' => 'Center punch', 'brand' => 'Gedore', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0],
            ['name' => 'Special adjustable wrench', 'brand' => 'Bahco', 'type' => '12"', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 0],
            ['name' => 'Adjustable wrench', 'brand' => 'Bahco', 'type' => '6"', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 1],
            ['name' => 'Adjustable wrench', 'brand' => 'Bahco', 'type' => '8"', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 3],
            ['name' => 'Small hand saw', 'brand' => 'Bahco', 'type' => '268', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 11],
            ['name' => 'Hand saw', 'brand' => 'Facom', 'type' => '601', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 3],
            ['name' => 'Square', 'brand' => 'Promat', 'type' => '250mm', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Large file', 'brand' => 'Carolus', 'type' => '200mm', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 5],
            ['name' => 'Half-round file', 'brand' => 'Carolus', 'type' => '200mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 11],
            ['name' => 'Flat file', 'brand' => 'Carolus', 'type' => '200mm', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 7],
            ['name' => 'Tube wrench', 'brand' => 'Gedore', 'type' => '13x17mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 4],
            ['name' => 'Tube wrench bar', 'brand' => 'Gedore', 'type' => '6-8-10-12-14', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 1],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'Gedore', 'type' => '19mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 15],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'Gedore', 'type' => '17mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 0],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'Gedore', 'type' => '13mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 2],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'Gedore', 'type' => '10mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 16],
            ['name' => 'Bit holder handle', 'brand' => 'Gedore', 'type' => '1/4x125', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 6],
            ['name' => 'Bit holder handle extension', 'brand' => 'Gedore', 'type' => '150mm', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 5],
            ['name' => 'Bit set', 'brand' => 'Metabo', 'type' => '302700', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 8],
            ['name' => 'Cable tie gun', 'brand' => 'Facom', 'type' => '968075', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 5],
            ['name' => 'Number punch 3', 'brand' => '', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Number punch 4', 'brand' => '', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Number punch 5', 'brand' => '', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Cable knife', 'brand' => 'Knipex', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 11],
            ['name' => 'Multimeter', 'brand' => 'Uni-T', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0],
            ['name' => 'Cable stripper', 'brand' => 'Kabifix', 'type' => 'FK 28', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0],
        ];

        $categoryIds = DB::table('categories')->pluck('id', 'name')->toArray();

        DB::table('tools')->insert(array_map(function ($tool) use ($categoryIds) {
            return [
                'name' => $tool['name'],
                'brand' => $tool['brand'],
                'type' => $tool['type'],
                'category_id' => $categoryIds[$tool['category']],
                'roletype' => $tool['roletype'],
                'amount_in_stock' => $tool['amount_in_stock'],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, $tools));
    }
}
