<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => '8X150 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 7, 'minimal_stock' => 3, 'replacement_cost' => 14.56],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => '5,5X125 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5, 'minimal_stock' => 3, 'replacement_cost' => 9.20],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => '4,0X100 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 9, 'minimal_stock' => 3, 'replacement_cost' => 8.06],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => '3,5X100 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 3, 'minimal_stock' => 2, 'replacement_cost' => 7.83],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => '2,5X75 VE', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 4, 'minimal_stock' => 2, 'replacement_cost' => 6.03],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => 'PZ2 AD', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 4, 'minimal_stock' => 2, 'replacement_cost' => 7.63],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => 'PZ1 AD', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 14, 'minimal_stock' => 5, 'replacement_cost' => 6.14],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => 'PZ0 AD', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 3, 'replacement_cost' => 9.24],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => 'PH0 AP', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5, 'minimal_stock' => 2, 'replacement_cost' => 7.94],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => 'PH1 AP', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 3, 'minimal_stock' => 2, 'replacement_cost' => 7.63],
            ['name' => 'Insulated screwdriver', 'brand' => 'GEDORE', 'type' => 'PH2 AP', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 1, 'minimal_stock' => 2, 'replacement_cost' => 9.20],
            ['name' => 'Voltage tester screwdriver', 'brand' => 'GEDORE', 'type' => 'yt-0404', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5, 'minimal_stock' => 3, 'replacement_cost' => 8.68],
            ['name' => 'Small phillips screwdriver', 'brand' => 'GEDORE', 'type' => 'PH1 X 25', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 3, 'minimal_stock' => 2, 'replacement_cost' => 5.22],
            ['name' => 'Small phillips screwdriver', 'brand' => 'GEDORE', 'type' => 'PH2 X 35', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 5, 'minimal_stock' => 2, 'replacement_cost' => 5.90],
            ['name' => 'Small flathead screwdriver', 'brand' => 'GEDORE', 'type' => '6,5X35', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 8, 'minimal_stock' => 3, 'replacement_cost' => 6.28],
            ['name' => 'Small flathead screwdriver', 'brand' => 'GEDORE', 'type' => '5,5X35', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 1, 'minimal_stock' => 2, 'replacement_cost' => 5.62],
            ['name' => 'Small flathead screwdriver', 'brand' => 'GEDORE', 'type' => '4X25', 'category' => 'Screwdrivers', 'roletype' => 'electrician', 'amount_in_stock' => 4, 'minimal_stock' => 2, 'replacement_cost' => 5.48],
            ['name' => 'Flathead screwdriver', 'brand' => 'GEDORE', 'type' => 'ANF 8x150', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 11, 'minimal_stock' => 5, 'replacement_cost' => 9.38],
            ['name' => 'Flathead screwdriver', 'brand' => 'GEDORE', 'type' => 'ANF 6,5 x 150', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 24, 'minimal_stock' => 5, 'replacement_cost' => 8.08],
            ['name' => 'Flathead screwdriver', 'brand' => 'GEDORE', 'type' => 'AN5,5X125', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 21, 'minimal_stock' => 5, 'replacement_cost' => 6.12],
            ['name' => 'Flathead screwdriver', 'brand' => 'GEDORE', 'type' => 'AN4,0X100', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 17, 'minimal_stock' => 5, 'replacement_cost' => 4.30],
            ['name' => 'Flathead screwdriver', 'brand' => 'GEDORE', 'type' => 'AN3,5X75', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 6, 'minimal_stock' => 3, 'replacement_cost' => 3.94],
            ['name' => 'Pozidriv screwdriver', 'brand' => 'GEDORE', 'type' => 'PZ1 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 14, 'minimal_stock' => 5, 'replacement_cost' => 6.93],
            ['name' => 'Pozidriv screwdriver', 'brand' => 'GEDORE', 'type' => 'PZ2 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 6, 'minimal_stock' => 3, 'replacement_cost' => 8.57],
            ['name' => 'Phillips screwdriver', 'brand' => 'GEDORE', 'type' => 'PH1 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 7, 'minimal_stock' => 3, 'replacement_cost' => 5.54],
            ['name' => 'Phillips screwdriver', 'brand' => 'GEDORE', 'type' => 'PH2 AND', 'category' => 'Screwdrivers', 'roletype' => 'ironworker', 'amount_in_stock' => 5, 'minimal_stock' => 3, 'replacement_cost' => 8.08],
            ['name' => 'Universal pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'shared', 'amount_in_stock' => 19, 'minimal_stock' => 5, 'replacement_cost' => 31.95],
            ['name' => 'Cutting pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'shared', 'amount_in_stock' => 6, 'minimal_stock' => 3, 'replacement_cost' => 47.00],
            ['name' => 'Electronic cutting pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 23.80],
            ['name' => 'Curved nose pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 17, 'minimal_stock' => 5, 'replacement_cost' => 45.05],
            ['name' => 'Self-adjusting crimping pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 4, 'minimal_stock' => 2, 'replacement_cost' => 196.85],
            ['name' => 'Terminal crimping pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 123.15],
            ['name' => 'Wire stripping pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 8, 'minimal_stock' => 3, 'replacement_cost' => 105.55],
            ['name' => 'Special wire stripping pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 2, 'minimal_stock' => 2, 'replacement_cost' => 80.85],
            ['name' => 'Pliers wrench', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 70.20],
            ['name' => 'Sleeving pliers', 'brand' => 'FACOM', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 7, 'minimal_stock' => 3, 'replacement_cost' => 158.72],
            ['name' => 'Cable shears', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 6, 'minimal_stock' => 3, 'replacement_cost' => 52.00],
            ['name' => 'Tube cutter', 'brand' => 'SKANDIA', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 12, 'minimal_stock' => 5, 'replacement_cost' => 42.00],
            ['name' => 'Waterpump pliers', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Pliers', 'roletype' => 'ironworker', 'amount_in_stock' => 9, 'minimal_stock' => 3, 'replacement_cost' => 39.50],
            ['name' => 'Crimping pliers', 'brand' => 'WEIDMULLE', 'type' => '', 'category' => 'Pliers', 'roletype' => 'electrician', 'amount_in_stock' => 1, 'minimal_stock' => 2, 'replacement_cost' => 218.28],
            ['name' => 'Drill bit set 1-13mm', 'brand' => 'LABOR', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 60.40],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '10mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 11.80],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '8mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 9.18],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '6mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 6.50],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '5mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 5.20],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '4mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 4.56],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '3mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 3.94],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '2.5mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 3.94],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '2mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 3.94],
            ['name' => 'Hex key', 'brand' => 'GEDORE', 'type' => '1.5mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 3.94],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '6mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 13, 'minimal_stock' => null, 'replacement_cost' => 5.02],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '7mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11, 'minimal_stock' => null, 'replacement_cost' => 5.27],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '8mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 14, 'minimal_stock' => null, 'replacement_cost' => 5.38],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '9mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 14, 'minimal_stock' => null, 'replacement_cost' => 5.38],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '10mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 5.38],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '11mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15, 'minimal_stock' => null, 'replacement_cost' => 5.53],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '12mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11, 'minimal_stock' => null, 'replacement_cost' => 5.89],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '13mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 3, 'minimal_stock' => null, 'replacement_cost' => 5.99],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '15mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11, 'minimal_stock' => null, 'replacement_cost' => 6.12],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '17mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 3, 'minimal_stock' => null, 'replacement_cost' => 6.35],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '19mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15, 'minimal_stock' => null, 'replacement_cost' => 6.48],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '22mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15, 'minimal_stock' => null, 'replacement_cost' => 6.82],
            ['name' => 'Ratchet socket', 'brand' => 'GEDORE', 'type' => '24mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 15, 'minimal_stock' => null, 'replacement_cost' => 19.32],
            ['name' => 'Ratchet socket 3/8"', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 12, 'minimal_stock' => null, 'replacement_cost' => 40.26],
            ['name' => 'Small extension', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 4, 'minimal_stock' => null, 'replacement_cost' => 6.59],
            ['name' => 'Large extension', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 11, 'minimal_stock' => null, 'replacement_cost' => 7.81],
            ['name' => 'Universal joint', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 12, 'minimal_stock' => null, 'replacement_cost' => 41.48],
            ['name' => 'Ratchet', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 40.26],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '19mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 39.93],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '18mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 37.39],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '17mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 35.79],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '16mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 35.79],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '13mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 27.74],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '12mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 27.42],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '11mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 26.52],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '10mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 1, 'replacement_cost' => 25.55],
            ['name' => 'Combination wrench', 'brand' => 'FACOM', 'type' => '8mm', 'category' => 'Sets', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 23.47],
            ['name' => 'Toolcase', 'brand' => 'FACOM', 'type' => 'BS T20BP', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 72.00],
            ['name' => 'Tool backpack', 'brand' => 'STANLEY', 'type' => 'Fat-Max', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 73.12],
            ['name' => '5M measuring tape', 'brand' => 'STANLEY', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 3, 'replacement_cost' => 5.38],
            ['name' => 'Caliper', 'brand' => 'MITUTOYO', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 39.00],
            ['name' => 'Hammer', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 18.05],
            ['name' => 'Level', 'brand' => 'STABILA', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 16, 'minimal_stock' => 5, 'replacement_cost' => 25.12],
            ['name' => 'Center punch', 'brand' => 'GEDORE', 'type' => '', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 5.60],
            ['name' => 'Special adjustable wrench', 'brand' => 'BAHCO', 'type' => '12"', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 67.59],
            ['name' => 'Adjustable wrench', 'brand' => 'BAHCO', 'type' => '6"', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 1, 'minimal_stock' => 2, 'replacement_cost' => 46.47],
            ['name' => 'Adjustable wrench', 'brand' => 'BAHCO', 'type' => '8"', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 3, 'minimal_stock' => 2, 'replacement_cost' => 47.76],
            ['name' => 'Small hand saw', 'brand' => 'BAHCO', 'type' => '268', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 11, 'minimal_stock' => 5, 'replacement_cost' => 19.24],
            ['name' => 'Hand saw', 'brand' => 'BAHCO', 'type' => '601', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 3, 'minimal_stock' => null, 'replacement_cost' => 36.26],
            ['name' => 'Square', 'brand' => 'MIB', 'type' => '250mm', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 25.00],
            ['name' => 'Large file', 'brand' => 'GEDORE', 'type' => '200mm', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 5, 'minimal_stock' => null, 'replacement_cost' => 10.71],
            ['name' => 'Half-round file', 'brand' => 'GEDORE', 'type' => '200mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 11, 'minimal_stock' => 5, 'replacement_cost' => 12.22],
            ['name' => 'Flat file', 'brand' => 'GEDORE', 'type' => '200mm', 'category' => 'Other', 'roletype' => 'shared', 'amount_in_stock' => 7, 'minimal_stock' => null, 'replacement_cost' => 13.44],
            ['name' => 'Tube wrench', 'brand' => 'GEDORE', 'type' => '13x17mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 4, 'minimal_stock' => null, 'replacement_cost' => 10.44],
            ['name' => 'Tube wrench bar', 'brand' => 'GEDORE', 'type' => '6-8-10-12-14', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 1, 'minimal_stock' => null, 'replacement_cost' => 6.88],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'GEDORE', 'type' => '19mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 15, 'minimal_stock' => 5, 'replacement_cost' => 22.89],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'GEDORE', 'type' => '17mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 0, 'minimal_stock' => 3, 'replacement_cost' => 21.76],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'GEDORE', 'type' => '13mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 2, 'minimal_stock' => 3, 'replacement_cost' => 17.10],
            ['name' => 'Spanner/ratchet wrench', 'brand' => 'GEDORE', 'type' => '10mm', 'category' => 'Other', 'roletype' => 'ironworker', 'amount_in_stock' => 16, 'minimal_stock' => 5, 'replacement_cost' => 15.50],
            ['name' => 'Bit holder handle', 'brand' => 'GEDORE', 'type' => '1/4x125', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 6, 'minimal_stock' => 3, 'replacement_cost' => 26.38],
            ['name' => 'Bit holder handle extension', 'brand' => 'GEDORE', 'type' => '150mm', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 5, 'minimal_stock' => 3, 'replacement_cost' => 19.06],
            ['name' => 'Bit set', 'brand' => 'BAHCO', 'type' => '302700', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 8, 'minimal_stock' => 3, 'replacement_cost' => 26.68],
            ['name' => 'Cable tie gun', 'brand' => 'FACOM', 'type' => '968075', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 5, 'minimal_stock' => 3, 'replacement_cost' => 97.67],
            ['name' => 'Number punch 3', 'brand' => 'PARTEX', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 1, 'replacement_cost' => 10.25],
            ['name' => 'Number punch 4', 'brand' => 'PARTEX', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 1, 'replacement_cost' => 10.25],
            ['name' => 'Number punch 5', 'brand' => 'PARTEX', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 1, 'replacement_cost' => 10.25],
            ['name' => 'Cable knife', 'brand' => 'KNIPEX', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 11, 'minimal_stock' => 5, 'replacement_cost' => 27.25],
            ['name' => 'Voltage test', 'brand' => 'BENNING', 'type' => '', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 3, 'replacement_cost' => 71.37],
            ['name' => 'Cable stripper', 'brand' => 'HAUPA', 'type' => 'FK 28', 'category' => 'Other', 'roletype' => 'electrician', 'amount_in_stock' => 0, 'minimal_stock' => 2, 'replacement_cost' => 69.64],
        ];

        $categoryIds = DB::table('categories')->pluck('id', 'name')->toArray();

        DB::table('tools')->insert(array_map(function ($tool) use ($categoryIds) {
            return [
                'name' => $tool['name'],
                'brand' => $tool['brand'],
                'type' => $tool['type'],
                'category_id' => $categoryIds[$tool['category']],
                'roletype' => $tool['roletype'],
                'amount_in_stock' => $tool['amount_in_stock'],
                'minimal_stock' => $tool['minimal_stock'],
                'replacement_cost' => $tool['replacement_cost'],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, $tools));
    }
}
